### ISSUE TITLE
Macropad Keyboard Interrupt

### ISSUE THREAD

**Issue by theturboferret** [deckerego/Macropad_4chord_MIDI#32]
Love the macropad code, but I have a rather infuriating issue - mine only runs for a few seconds!

I have updated the macropad to CircuitPython 8.0.5, and copied every file from the Macropad.4chord.MIDI.v2.3.0.zip onto the pad without issues, and it fires up perfectly.  However after a couple of seconds I get the message: 
(snake emoji)64@code.py Keyboard
KeyboardInterrupt:

Code done running.

then:
(snake emoji)Done | 8.0.5
Press any key to ente
r the REPL. Use CTRL-
D to reload.

then:
(snake emoji)REPL | 8.0.5
n 8.0.5 on 2023-03-31
; Adafruit Macropad R
P2040 with rp2040
>>> M105

The M105 continues repeating indefinitely

The only differences between the contents of my Macropad and your zip file is the presence of a file called settings.toml in addition to the settings.py, plus a bootout.txt containing:

Adafruit CircuitPython 8.0.5 on 2023-03-31; Adafruit Macropad RP2040 with rp2040
Board ID:adafruit_macropad_rp2040
UID:DF60BCA0036F5434
boot.py output:
Mounting Read-Only

I am a total noob blindly following instructions with zero knowledge of code or what I'm doing, so apologies if this is an obvious thing that anyone with any clue should know how to resolve!

Many thanks :)

**Comment by deckerego** [comment]
Just re-tested with CircuitPython 8.0.5 and 4chord MIDI 2.3.0 - confirmed that should work.

Not sure why you have a file `settings.toml` in the MacroPad - that's pretty strange.

It sounds like maybe there was an old set of files that needs to get wiped out first. Would recommend taking the following steps:

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/532789/230665192-a1fbd8b8-1e1c-4a7e-828e-d6ab77a7a5dc.png">

**Comment by deckerego** [comment]
One other idea - for some strange reason it appears the "M105" message can happen when running 3d printing utilities:
https://forums.adafruit.com/viewtopic.php?p=909834

Very strange - it seems like some software will try to reach out to any communication ports listed, of which the Macropad (running on a tty) is one.

**Comment by theturboferret** [comment]
ooh, quitting Cura has solved all issues :)  I'm using this on my Mac which is mainly used for slicing 3D prints....who would have thought it!

Many thanks for the assistance
